environment:
  SSL_CERT_FILE: C:\ca\cacert.pem
  COVERALLS_REPO_TOKEN:
    secure: sR+OO2wYopy1MdZX+asECm56PinUUuIHNQXcAfSmVlf6lw6y4I5jOiby5IqsuwyP
  GITHUB_TOKEN:
    secure: LWCRPexJEGMkW0f8ku8Q45CPnQDCi4sgyi/cFdOHizI9ToLlDYozXxI21bD9cDU4
  github_username: serialseb
  github_password:
    secure:
      1lXaOJ0GvCAOd0O9DDvVqw2eb7TvP2jve12u3hD2g4J7RVW2c2jC5XuRFyEuduUA
  coverity_token:
    secure: xZnMqxFHZN9mENgS6gGTtlz7hadzkcHVgp5HRGML4XY=
  coverity_email:
    secure: cd97kb3eIDThYbzxEJHk/YADgHwcEwE5aRS05A0GB/4=

assembly_info:
  patch: false
  file: src\CommonInfo.cs
  assembly_version: $(AssemblyMajor).0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

platform: Any CPU

cache:
  - packages -> **\packages.config

install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - ps: mkdir c:\ca; iwr http://curl.haxx.se/ca/cacert.pem -outfile C:\ca\cacert.pem
  - set SSL_CERT_FILE=C:\ca\cacert.pem
  - ps: build/Set-Version.ps1

before_build:
  - nuget restore src/ConsulStructure.sln

build:
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  project: src/ConsulStructure.sln

build_script:
  - ps: echo (get-location)
  - ps: build/Build-Solution.ps1

after_build:
  - ps: build/Publish-Coverity.ps1
  - ps: build/Create-Package.ps1

artifacts:
 - path: src/openrasta/bin/$(configuration)/*.dll
   name: dlls
 - path: src/openrasta/bin/$(configuration)/*.pdb
   name: pdbs
 - path: '*.nupkg'
 - path: opencoverCoverage.xml
 - path: coverity.zip
   name: Coverity Build

test_script:
- ps: build/Test-Code.ps1

deploy:
 - provider: NuGet
   api_key:
     secure: KAawIkFXgAsCh3eqjDd2N/epoJ8fW12RMSZpEaaqPZvlwlEEGdxanyxCFXccnvMa
   skip_symbols: true
   artifact: /.*\.nupkg/
   on:
     appveyor_repo_tag: true